version: "2.3"
services:
  r_centernet2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    shm_size: "64gb"
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /home/server1/workdir/project_ing/SK_temp/AIStages/RecycleDetection/:/home/RecycleDetection/

    environment:
      - DISPLAY=unix$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
    # Uncomment with proper source to access webcam from docker
#    devices:
#      - /dev/video0:/dev/video0
