_BASE_: "Base-CenterNet2.yaml"
MODEL:
  BACKBONE:
    NAME: "build_res2net_bifpn_backbone"
  BIFPN:
    NUM_BIFPN: 7
    OUT_CHANNELS: 288
  WEIGHTS: "output/CenterNet2_R2-101-DCN-BiFPN_4x+4x_1560_ST.pth"
  RESNETS:
    DEPTH: 101
    WIDTH_PER_GROUP: 26
    DEFORM_ON_PER_STAGE: [False, False, True, True] # on Res4, Res5
    DEFORM_MODULATED: True
  PIXEL_MEAN: [110.07439221, 117.39781397, 123.65060953] # [123.675, 116.280, 103.530]
  PIXEL_STD: [54.77174141, 53.35981744, 54.01141646]  # [58.395, 57.12, 57.375]
  CENTERNET:
    USE_DEFORMABLE: True
  ROI_HEADS:
    IN_FEATURES: ["p3", "p4"]
TEST:
  EVAL_PERIOD: 600
SOLVER:
  MAX_ITER: 18000 # 1epoch 600
  CHECKPOINT_PERIOD: 600
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 0.01 # 0.04
  IMS_PER_BATCH: 8  # 32
DATASETS:
  TRAIN: "('recycle_train',)"
  TEST: "('recycle_val',)"
  TRAINPATH: "/home/RecycleDetection/dataset/train.json"
  TESTPATH: "/home/RecycleDetection/dataset/train.json"
INPUT:
  FORMAT: RGB
  CUSTOM_AUG: EfficientDetResizeCrop
  TRAIN_SIZE: 640 # 1280
  TEST_SIZE: 640 # 1560
  TEST_INPUT_TYPE: 'square'
  